# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deno-react CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: pwd
        run: ls -al
      - name: Yarn install
        run: cd frontend && yarn install
      - name: tsc
        run: yarn tsc
      - name: lint
        run: yarn lint
      - name: build
        run: yarn build:frontend
