# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deno-react CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Deno environment
        uses: denolib/setup-deno@master
        with:
          deno-version: v1.1.0
      - name: Set up Node
        uses: actions/setup-node@v1 
      - name: Yarn install
        run: cd frontend && yarn install
      - name: tsc
        run: yarn tsc
      - name: test
        run: yarn test
      - name: lint
        run: deno lint --unstable ./server ./frontend
      - name: build
        run: yarn build
