# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deno-react CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v1  
      - name: install deno
        uses: deno lint
      - name: Yarn install
        run: cd frontend && yarn install
      - name: tsc
        run: yarn tsc
      - name: test
        run: yarn test
      - name: deno lint
        run: deno lint --unstable
      - name: build
        run: yarn build
